services:
  backend:
    image: php-backend
    build: ./backend
    volumes:
      - ./backend/img/photos:/var/www/html/img/photos
      - ./backend/img/thumbs:/var/www/html/img/thumbs
      - ./backend/laravel/.env:/var/www/html/laravel/.env:ro
    ports:
      - "8001:80"


  mysql:
    image: mysql:9.4
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
